/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/
using System;

public class Solution {
    public static char FindTheDifference(string s, string t) {
        // 由于t中含有s中所有的字符，
        // 我们只需要把t中所有字符的ASCII和减去S中所有字符的ASCII码和，差就是那个多的字符
        // 题目限制条件是s的长度不大于1000，所以不会溢出
        int s_sum = 0;
        int t_sum = 0;
        for (int i = 0; i < s.Length; i++) {
            s_sum += (int)(s[i]);
            t_sum += (int)(t[i]);
        }

        t_sum += (int)(t[t.Length - 1]);
        return (char)(t_sum - s_sum);
    }

    public static char FindTheDifference2(string s, string t) {
        // 不溢出的版本

        int remaining = 0;
        for (int i = 0; i < s.Length; i++) {
            remaining +=((int)t[i] - (int)s[i]);
        }

        remaining += (int)(t[t.Length - 1]);
        return (char)(remaining);
    }

    public static void Main(string[] args){
        string s = "abcd";
        string t = "abcde";
        Console.WriteLine($"Char '{FindTheDifference(s, t)}' in '{t}' of '{s}'");

        Console.WriteLine($"Char '{FindTheDifference2(s, t)}' in '{t}' of '{s}'");
    }
}